//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIzzaNC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MizzaToppingStyle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MizzaToppingStyle()
        {
            this.MizzaToppingsStyleSKUs = new HashSet<MizzaToppingsStyleSKU>();
        }
    
        public string ToppingStyleID { get; set; }
        public string ToppingName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MizzaToppingsStyleSKU> MizzaToppingsStyleSKUs { get; set; }
    }
}
