//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIzzaNC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MizzaToppingSKUPrice
    {
        public string ToppingStyleID { get; set; }
        public string SKUID { get; set; }
        public int Price { get; set; }
    
        public virtual MizzaToppingsStyleSKU MizzaToppingsStyleSKU { get; set; }
    }
}
