//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIzzaNC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MizzaSKU
    {
        public string MizzaSKUID { get; set; }
        public string MizzaSKUName { get; set; }
        public string MizzaStyleID { get; set; }
        public string MizzaSizeID { get; set; }
    
        public virtual MizzaSize MizzaSize { get; set; }
        public virtual MizzaStyle MizzaStyle { get; set; }
        public virtual MizzaSkuBasePrice MizzaSkuBasePrice { get; set; }
        public virtual MizzaSKUStock MizzaSKUStock { get; set; }
    }
}
