//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIzzaNC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MIzzaNextEntities : DbContext
    {
        public MIzzaNextEntities()
            : base("name=MIzzaNextEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MizzaSize> MizzaSizes { get; set; }
        public virtual DbSet<MizzaSKU> MizzaSKUs { get; set; }
        public virtual DbSet<MizzaSkuBasePrice> MizzaSkuBasePrices { get; set; }
        public virtual DbSet<MizzaSKUStock> MizzaSKUStocks { get; set; }
        public virtual DbSet<MizzaStyle> MizzaStyles { get; set; }
        public virtual DbSet<MizzaToppingSKUPrice> MizzaToppingSKUPrices { get; set; }
        public virtual DbSet<MizzaToppingSKUStock> MizzaToppingSKUStocks { get; set; }
        public virtual DbSet<MizzaToppingsStyleSKU> MizzaToppingsStyleSKUs { get; set; }
        public virtual DbSet<MizzaToppingStyle> MizzaToppingStyles { get; set; }
    }
}
